### ISSUE TITLE
Cannot load DLL file '/usr/libEntities.so'

### ISSUE THREAD

**Issue by jmcerrejon** [tx00100xt/serioussam-packages#1]
Howdy!

First of all, thanks for your work. Very impressive and I'm a very big fan of the game! 😉

Tried to install it on _Raspberry Pi OS 64 bits_ using the binary: _serioussamclassic-1.10.4-1_rpi4b_arm64.deb_. All OK.

I copy the game data files at _/home/my_user/.local/share/Serious-Engine/serioussam_ and the message about _/usr/libEntities.so_ appear.
The place of the file really is: _/usr/lib/aarch64-linux-gnu/serioussam/libEntities.so_

Same with the file libGame.so. If I move the files to /usr, the game run with no hassle.

![2023-04-29-182244_1920x1080_scrot](https://user-images.githubusercontent.com/1942431/235316814-3aaecbf6-e82c-4082-a47c-e03ed0868f81.png)

**Comment by tx00100xt** [comment]
> I copy the game data files at _/home/my_user/.local/share/Serious-Engine/serioussam_ and the message about _/usr/libEntities.so_

That's my fault. I checked the work of all .debs
files (include Raspberry Pi 3B files), except for the Raspberry Pi 4 files. I forgot to add the latest patch when compiling.
https://github.com/tx00100xt/SeriousSamClassic/commit/f7e646904cbd102928914b58a6bf348689d9758b
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/56118c6edb140d07f09e5c2c970426feeb416f84

During the day, I will rebuilding the packages and update them in
https://github.com/tx00100xt/serioussam-packages
Thanks for reporting the problem.

**Comment by tx00100xt** [comment]
Ready.
Files:
* [serioussamclassic-1.10.4-1_rpi4b_am64.deb](https://github.com/tx00100xt/serioussam-packages/raw/main/RasberryPiOS/RPi4B/arm64/serioussamclassic-1.10.4-1_rpi4b_arm64.deb)  
* [serioussamclassic-vk-1.10.4-1_rpi4b_am64.deb](https://github.com/tx00100xt/serioussam-packages/raw/main/RasberryPiOS/RPi4B/arm64/serioussamclassic-vk-1.10.4-1_rpi4b_arm64.deb)  
Updated.

**Comment by jmcerrejon** [comment]
Thanks, dude! 👏

**Comment by tx00100xt** [comment]
I also really like this game. It's good that everything works. Thanks again for pointing out the problem. Have a nice game.
